switch to publish trigger

diff --git a/.github/workflows/build-docs.yml b/.github/workflows/build-docs.yml
--- a/.github/workflows/build-docs.yml
+++ b/.github/workflows/build-docs.yml
@@ -1,34 +1,29 @@
 name: build-docs
 
 on:
-  push:
-    branches:
-      - master
+  release:
+    types: [published]
 
 jobs:
   build:
     runs-on: ubuntu-18.04
-    strategy:
-      fail-fast: false
 
     steps:
     - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
     - name: Set up Python 3.6
       uses: actions/setup-python@v2
       with:
         python-version: 3.6
 
-    - name: Setup Github config and pages branch
-      run: |
-        git config user.email "$(git log -1 --pretty=format:'%ae')"
-        git config user.name "$(git log -1 --pretty=format:'%an')"
-        git config pull.rebase true
-        git checkout -b pages || git checkout pages
-        git pull origin pages || echo "do nothing" > /dev/null
+#    - name: Setup Github config and pages branch
+#      run: |
+#        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
+#        git config user.name github-actions[bot]
+#        git config pull.rebase true
+#        git checkout -b pages || git checkout pages
+#        git pull origin pages || echo "do nothing" > /dev/null
       # Last two lines are to handle cases where the local and remote "pages"
-      # branch do and don't exist without causing workflow failure
+      # branch do and don't exist without causing workflow failure (all cases should work)
 
     - name: Install dependencies
       run: |
@@ -41,19 +36,23 @@ jobs:
 
     - name: Build sphinx documentation
       run: |
+        git checkout -b pages
         sudo apt-get install build-essential
         make -C docs-source html
+        rm -rf ./docs
+        cp -r ./docs-source/build/html ./docs
+
 
 ### Uncomment to upload sphinx documentation as an artifact
-#    - name: Upload sphinx html documentation
+#    - name: Upload sphinx html documentation artifact
 #      uses: actions/upload-artifact@v1
 #      with:
 #        name: DocumentationHTML
-#        path: docs-source/build/html/
+#        path: ./docs
 
     - name: Commit documentation changes
       run:  |
-        git add ./docs-source/build --force
+        git add ./docs
         git commit -m "Documentation build via Github Actions"
 
     - name: Push documentation changes to "pages" branch
@@ -62,9 +61,10 @@ jobs:
         branch: pages
         github_token: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Create PR
-      uses: peter-evans/create-pull-request@v3
-      with:
-        branch: pages
-        base: master
-        title: Documentation changes by create-pull-request action
+### Works, but seems to auto-close PRs if workflow is activated again before merge
+#    - name: Create PR
+#      uses: peter-evans/create-pull-request@v3
+#      with:
+#        branch: pages
+#        base: master
+#        title: Documentation changes by create-pull-request action
